version: '3.3'
services:
  apps:
    container_name: docker-my-spring2
    image: spring-redis:v3
    build: .
    env_file:
      - .env
    ports:
      - "8082:8082"
    links:
      - redis
      - rabbitmq5
    volumes:
      - C:\Users\vishn\IdeaProjects\RedisProject\logs:/log

  redis:
    container_name: redis2
    image: redis:latest
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"

  rabbitmq5:
    container_name: rabbitmq2
    image: 'rabbitmq:3.10.5-management-alpine'
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"






